module:
  module.hugoVersion:
    extended: true
    min: '0.88.1'
baseURL: 'https://www.focusotter.cloud'
# theme: 'up-business-theme'
languageCode: 'en-us'
enableEmoji: true
title: 'Focus Otter'

# googleAnalytics: ""

summaryLength: 20

params:
  title: 'Focus Otter'
  description: 'Fullstack solutions for todays modern developer. Where modern frontend development meets the scalability of AWS'
  images:
    - 'images/hero-image.png'

  logo: 'logo.png'

  social:
    twitter: 'https://twitter.com/intent/follow?screen_name=focusotter'

  contact:
    - 'mtliendo@focusotter.com'

  copyright: '© 2023 Focus Otter All Rights Reserved'

menus:
  main:
    - name: 'Home'
      url: '/#hero'
      weight: 1

    - name: 'Blog'
      url: '/blog'
      weight: 2

    - name: 'Shop'
      url: '/shop'
      weight: 3

  buttons:
    - name: 'Book a call'
      url: '/#'
      weight: 3
      pre: 'btn btn-primary text-light'

  footer:
    - name: 'Home'
      url: '/#hero'
      weight: 1

    - name: 'Blog'
      url: '/blog'
      weight: 2

taxonomies:
  series: 'series'
  tags: 'tags'
